import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  races: defineTable({
    key: v.string(),
    name: v.string(),
    office: v.string(),
    state: v.string(),
    electionDate: v.string(),
    candidates: v.array(
      v.object({
        name: v.string(),
        campaignDomain: v.string(),
        advertiserId: v.string(),
      }),
    ),
    updatedAt: v.number(),
  }).index("by_key", ["key"]),
  captureRuns: defineTable({
    raceId: v.id("races"),
    source: v.union(v.literal("ads"), v.literal("news"), v.literal("trends")),
    status: v.union(
      v.literal("succeeded"),
      v.literal("failed"),
      v.literal("updating"),
    ),
    query: v.string(),
    parameters: v.record(v.string(), v.string()),
    capturedAt: v.number(),
    resultCount: v.number(),
    rawStorageId: v.optional(v.id("_storage")),
    errorMessage: v.optional(v.string()),
  }).index("by_race_source_captured", ["raceId", "source", "capturedAt"]),
  adCreatives: defineTable({
    raceId: v.id("races"),
    captureId: v.id("captureRuns"),
    candidateName: v.optional(v.string()),
    advertiser: v.string(),
    advertiserId: v.string(),
    creativeId: v.string(),
    format: v.string(),
    detailsLink: v.string(),
    previewImage: v.optional(v.string()),
    targetDomain: v.optional(v.string()),
    detailsRawStorageId: v.optional(v.id("_storage")),
    creativeTitle: v.optional(v.string()),
    creativeHeadline: v.optional(v.string()),
    creativeLongHeadline: v.optional(v.string()),
    creativeSnippet: v.optional(v.string()),
    callToAction: v.optional(v.string()),
    visibleLink: v.optional(v.string()),
    destinationUrl: v.optional(v.string()),
    mediaUrl: v.optional(v.string()),
    videoUrl: v.optional(v.string()),
    videoDuration: v.optional(v.string()),
    detailsFetchedAt: v.optional(v.number()),
    firstShown: v.optional(v.number()),
    lastShown: v.optional(v.number()),
    minimumViews: v.optional(v.number()),
    maximumViews: v.optional(v.number()),
    minimumSpend: v.optional(v.string()),
    maximumSpend: v.optional(v.string()),
  }).index("by_capture", ["captureId"]),
  advertiserProfiles: defineTable({
    raceId: v.id("races"),
    captureId: v.optional(v.id("captureRuns")),
    candidateName: v.string(),
    advertiserName: v.string(),
    advertiserId: v.string(),
    profileUrl: v.string(),
    source: v.union(
      v.literal("serpapi_ads_capture"),
      v.literal("public_google_profile_snapshot"),
    ),
    scopeLabel: v.string(),
    reportedSpend: v.optional(v.number()),
    currency: v.optional(v.string()),
    reportedAdCount: v.optional(v.number()),
    regionalSpend: v.optional(
      v.array(
        v.object({
          region: v.string(),
          reportedSpend: v.optional(v.number()),
          reportedLabel: v.string(),
        }),
      ),
    ),
    formatBreakdown: v.optional(
      v.array(
        v.object({
          format: v.string(),
          percent: v.number(),
          reportedSpend: v.optional(v.number()),
          reportedLabel: v.string(),
        }),
      ),
    ),
    delayNote: v.optional(v.string()),
    capturedAt: v.number(),
    dataQualityNote: v.string(),
  }).index("by_race_captured", ["raceId", "capturedAt"]),
  newsItems: defineTable({
    raceId: v.id("races"),
    captureId: v.id("captureRuns"),
    title: v.string(),
    outlet: v.string(),
    url: v.string(),
    dateLabel: v.optional(v.string()),
    snippet: v.optional(v.string()),
  }).index("by_capture", ["captureId"]),
  trendObservations: defineTable({
    raceId: v.id("races"),
    captureId: v.id("captureRuns"),
    term: v.string(),
    latestValue: v.optional(v.number()),
    isPartial: v.boolean(),
  }).index("by_capture", ["captureId"]),
  evidenceChanges: defineTable({
    raceId: v.id("races"),
    captureId: v.id("captureRuns"),
    kind: v.union(
      v.literal("new_creative"),
      v.literal("new_advertiser"),
      v.literal("activity_increase"),
      v.literal("issue_context"),
    ),
    reportable: v.boolean(),
    rule: v.string(),
    evidenceUrls: v.array(v.string()),
    createdAt: v.number(),
  }).index("by_race_created", ["raceId", "createdAt"]),
  searchBudgets: defineTable({
    checkedAt: v.number(),
    totalSearchesLeft: v.number(),
    monthlyUsage: v.optional(v.number()),
    monthlyLimit: v.optional(v.number()),
    renewalDate: v.optional(v.string()),
  }).index("by_checked", ["checkedAt"]),
  evidenceBriefs: defineTable({
    raceId: v.id("races"),
    captureId: v.id("captureRuns"),
    question: v.string(),
    outcome: v.union(v.literal("answer"), v.literal("refusal")),
    headline: v.optional(v.string()),
    plainSummary: v.optional(v.string()),
    whatChanged: v.string(),
    watchNext: v.optional(v.string()),
    supportingEvidence: v.array(
      v.object({
        recordId: v.string(),
        title: v.string(),
        sourceUrl: v.string(),
      }),
    ),
    cannotConclude: v.string(),
    refusal: v.optional(v.string()),
    modelId: v.string(),
    createdAt: v.number(),
  }).index("by_race_created", ["raceId", "createdAt"]),
});
