"use client";

import { useEffect, useMemo, useState } from "react";
import { ConvexProvider, ConvexReactClient, useAction, useQuery } from "convex/react";
import { api } from "../convex/_generated/api";

type Layer = "ads" | "news" | "search";
type RecordItem = { id: string; kind: "ad" | "news"; label: string; note: string; url: string; creative?: any; news?: any };

const convexUrl = process.env.NEXT_PUBLIC_CONVEX_URL;
const convex = convexUrl ? new ConvexReactClient(convexUrl) : null;
const layers = {
  ads: { name: "Public ad activity", note: "Google Ads Transparency readings", color: "cyan" },
  news: { name: "News context", note: "Google News evidence records", color: "lime" },
  search: { name: "Search attention", note: "Google Trends comparison", color: "orange" },
} as const;

function StationMark() { return <svg className="station-mark" viewBox="0 0 48 48" aria-hidden="true"><circle cx="24" cy="24" r="21"/><path d="M16 34h16M19 34l3-17h4l3 17M20 24h8M24 10v7M17 15l7-5 7 5"/><circle cx="24" cy="10" r="1.7" fill="currentColor"/></svg>; }
function formatDate(value?: number) { return value ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)) : "Date not displayed"; }
function formatMoney(value?: number, currency = "USD") { return typeof value === "number" ? new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(value) : "Not displayed"; }

function Radar({ layer, points }: { layer: Layer; points: number }) {
  const locations = [[275,133],[372,202],[335,332],[194,302],[170,194],[412,286],[238,350],[423,154]];
  const dots = locations.slice(0, Math.max(1, Math.min(points || 1, locations.length)));
  return <div className={`radar ${layers[layer].color}`} aria-label={`${layers[layer].name} radar`}>
    <div className="radar-meta"><span>42.96° N / 87.91° W</span><span>LIVE SOURCE WINDOW · {new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date())}</span></div>
    <svg viewBox="0 0 600 480" role="img" aria-label={`${layers[layer].name} visualized as a field reading`}>
      <path className="contour" d="M86 212C80 124 180 69 300 73c129 4 221 53 216 139-3 69-69 117-83 179-17 75-103 83-172 70-82-16-165-54-175-146Z"/><path className="contour" d="M111 217c-2-70 86-119 190-122 114-4 191 38 191 117 0 62-56 103-72 153-15 51-89 65-153 49-74-19-154-50-156-147Z"/><path className="contour" d="M141 225c8-56 84-98 164-98 89 0 158 30 160 97 2 47-42 80-60 118-20 42-77 51-134 34-60-18-142-48-130-134Z"/>
      <g className="axis"><path d="M300 52v376M112 240h376M166 106l268 268M166 374l268-268"/></g><circle className="ring outer" cx="300" cy="240" r="145"/><circle className="ring middle" cx="300" cy="240" r="100"/><circle className="ring inner" cx="300" cy="240" r="55"/><path className="beam" d="M300 240 444 149A171 171 0 0 1 461 240Z"/>
      {dots.map(([cx, cy], i) => <circle className="signal" cx={cx} cy={cy} r={i % 3 === 0 ? 5 : 4} key={`${cx}-${cy}`}/>)}<circle className="core-halo" cx="300" cy="240" r="18"/><circle className="core" cx="300" cy="240" r="7"/>
    </svg>
    <span className="compass north">N</span><span className="compass east">E</span><span className="compass south">S</span><span className="compass west">W</span>
    <div className="radar-readout"><span>ACTIVE CHANNEL</span><strong>{layers[layer].name}</strong><em>{points ? `${points} stored readings` : "Awaiting first reading"}</em></div><p className="radar-foot">Each point is a stored public record—not an inference about voters.</p>
  </div>;
}

function FieldStation() {
  const demoRaces = useQuery(api.campaignWeather.listDemoRaces);
  const [raceKey, setRaceKey] = useState("wi-governor-2026");
  const radar = useQuery(api.campaignWeather.getRaceRadar, { key: raceKey });
  const refreshRace = useAction(api.ingestion.refreshRace);
  const [layer, setLayer] = useState<Layer>("ads"); const [pressDesk, setPressDesk] = useState(false); const [fetchOpen, setFetchOpen] = useState(false);
  const [refreshing, setRefreshing] = useState(false); const [refreshMessage, setRefreshMessage] = useState<string | null>(null); const [selectedId, setSelectedId] = useState<string | null>(null);
  const records = useMemo<RecordItem[]>(() => {
    if (!radar) return [];
    const ads = (radar.creatives ?? []).map((creative: any) => ({ id: `ad-${creative._id}`, kind: "ad" as const, label: `${creative.candidateName ?? creative.advertiser} creative`, note: `${creative.format} · ${creative.maximumViews ? `${creative.maximumViews.toLocaleString()} max observed shows` : "provider range not displayed"}`, url: creative.detailsLink, creative }));
    const news = (radar.newsItems ?? []).map((item: any) => ({ id: `news-${item._id}`, kind: "news" as const, label: item.title, note: `${item.outlet}${item.dateLabel ? ` · ${item.dateLabel}` : ""}`, url: item.url, news: item }));
    const trends = (radar.trendItems ?? []).map((trend: any) => ({ id: `trend-${trend._id}`, kind: "news" as const, label: `${trend.term} search interest`, note: trend.latestValue === undefined ? "Latest index not displayed" : `Latest Google Trends index: ${trend.latestValue}`, url: "https://trends.google.com/trends/", news: trend }));
    return layer === "ads" ? ads : layer === "news" ? news : trends;
  }, [radar, layer]);
  useEffect(() => { setSelectedId(null); }, [layer, raceKey]);
  const selected = records.find(item => item.id === selectedId) ?? records[0]; const activeRace = radar?.race; const activeDemo = demoRaces?.find(race => race.key === raceKey);
  const latestCapture = radar?.captures?.[layer === "search" ? "trends" : layer]; const pointCount = records.length;
  async function fetchLiveEvidence() { setRefreshing(true); setRefreshMessage(null); try { const outcome = await refreshRace({ raceKey }); setRefreshMessage(outcome.status === "complete" ? `Capture complete. ${outcome.outcomes?.ads?.count ?? 0} ad records, ${outcome.outcomes?.news?.count ?? 0} news records, and ${outcome.outcomes?.trends?.count ?? 0} trend readings were stored.` : outcome.reason ?? "The capture did not complete."); } catch (error) { setRefreshMessage(error instanceof Error ? error.message : "The capture did not complete."); } finally { setRefreshing(false); } }
  return <main className="station-shell">
    <header className="topbar"><button className="brand" onClick={() => setPressDesk(false)} aria-label="Open Voter Radar"><StationMark/><span><b>Campaign Weather</b><small>Great Lakes Field Station</small></span></button><div className="race-title"><b>{activeRace?.name ?? activeDemo?.name ?? "Wisconsin Governor 2026"}</b><small>{(activeRace?.candidates ?? []).map((candidate: any) => candidate.name).join(" / ") || activeDemo?.candidates.join(" / ")}</small></div><div className="capture"><i/>SOURCE-BOUND EVIDENCE</div><label className="race-switch"><span className="sr-only">Choose a demo race</span><select value={raceKey} onChange={event => { setRaceKey(event.target.value); setFetchOpen(false); setRefreshMessage(null); }}><option value="wi-governor-2026">Wisconsin Governor</option>{demoRaces?.filter(race => race.key !== "wi-governor-2026").map(race => <option value={race.key} key={race.key}>{race.name}</option>)}</select></label><button className="fetch-trigger" onClick={() => setFetchOpen(value => !value)} aria-expanded={fetchOpen}><span className="fetch-dot"/>Fetch race</button></header>
    {fetchOpen && <section className="fetch-panel" aria-label="Live race capture controls"><div><p>LIVE DEMO CAPTURE</p><h2>{activeDemo?.name ?? "Selected race"}</h2><span>{activeDemo?.candidates.join(" · ")}</span></div><div className="fetch-proof"><b>2 verified advertiser IDs</b><span>+ Google News + Google Trends</span></div><div className="fetch-proof"><b>Up to {activeDemo?.estimatedSearches ?? 4} searches</b><span>Account API runs free; 40-search reserve stays protected.</span></div><button className="live-button" onClick={fetchLiveEvidence} disabled={refreshing}>{refreshing ? "Capturing live records…" : "Fetch live evidence"}</button>{refreshMessage && <p className="fetch-result" role="status">{refreshMessage}</p>}</section>}
    {pressDesk ? <PressDesk radar={radar} onReturn={() => setPressDesk(false)} /> : <section className="radar-page"><aside className="channel-rail"><div className="rail-title"><b>Voter Radar</b><small>SELECT A SOURCE LAYER</small></div>{(Object.keys(layers) as Layer[]).map((key, index) => <button className={`channel ${layer === key ? "active" : ""}`} key={key} onClick={() => setLayer(key)}><i>{String(index + 1).padStart(2, "0")}</i><span><b>{layers[key].name}</b><small>{layers[key].note}</small></span></button>)}<div className="issue-note"><b>Issue lenses</b><p>Available after a transparent evidence review. This first slice does not label ads by issue or claim voter sentiment.</p></div><div className="legend"><span><i className="cyan-dot"/>source-bound record</span><span><i className="hollow-dot"/>context only</span><span><i className="cross"/>not a voter inference</span></div></aside><Radar layer={layer} points={pointCount}/><aside className="logbook"><div className="logbook-title"><b>Field log</b><small>{latestCapture ? formatDate(latestCapture.capturedAt) : "NO CAPTURE YET"}</small></div><div className="entries">{records.length ? records.slice(0, 8).map(record => <button className={`entry ${selected?.id === record.id ? "selected" : ""}`} key={record.id} onClick={() => setSelectedId(record.id)}><i className={record.kind === "ad" ? "cyan" : "lime"}/><span><small>{record.kind === "ad" ? "AD ACTIVITY" : layer === "search" ? "SEARCH ATTENTION" : "NEWS CONTEXT"}</small><b>{record.label}</b><em>{record.note}</em></span></button>) : <div className="empty-log"><b>No {layers[layer].name.toLowerCase()} stored</b><p>Choose “Fetch race” to make a source-bound live capture for this verified demo race.</p></div>}</div><footer>Capture source: SerpApi<br/>Raw provider records retained</footer></aside><section className="instrument-row"><button onClick={() => setFetchOpen(true)}><span className="instrument-index">01</span><span><b>Live capture</b><small>{radar ? "Refresh a comparable snapshot" : "Establish the first snapshot"}</small><em>FETCH RACE · UP TO 4 SEARCHES</em></span></button><button onClick={() => setPressDesk(true)}><span className="instrument-index">02</span><span><b>Comparison rules</b><small>New creative, advertiser, observed activity increase, or issue context</small><em>PRESS DESK · THRESHOLDS OPEN</em></span></button><button onClick={() => setPressDesk(true)}><StationMark/><span><b>Press Desk</b><small>Neutral brief and source ledger</small><em>READ THE EVIDENCE →</em></span></button></section><RecordPassport record={selected} profile={radar?.advertiserProfiles?.find((profile: any) => profile.candidateName === selected?.creative?.candidateName)} /><div className="bottom-strip"><span>CAMPAIGN WEATHER / AI-ASSISTED CIVIC EVIDENCE INFRASTRUCTURE</span><p>Browse-only. No voter profiles, targeting, advice, predictions, or inferred political preferences.</p></div></section>}
  </main>;
}

function RecordPassport({ record, profile }: { record?: RecordItem; profile?: any }) {
  if (!record) return <aside className="passport"><div><b>Evidence bay</b><small>WAITING FOR A RECORD</small></div><h2>No reading selected</h2><p>Fetch a verified race to store source-linked public records here.</p></aside>;
  if (record.kind === "news") return <aside className="passport"><div><b>{record.news?.term ? "Search reading" : "Evidence record"}</b><small>SELECTED PUBLIC CONTEXT</small></div><h2>{record.label}</h2><p>{record.news?.snippet ?? record.note}</p><a href={record.url} target="_blank" rel="noreferrer">Open public source ↗</a></aside>;
  const creative = record.creative;
  return <aside className="passport"><div><b>Ad Passport</b><small>SELECTED PUBLIC CREATIVE</small></div>{creative.previewImage && <img className="creative-preview" src={creative.previewImage} alt={`Public preview for ${record.label}`} />}<h2>{record.label}</h2><p>{creative.targetDomain ? `Destination shown: ${creative.targetDomain}` : record.note}</p><div className="reading-pairs"><span><small>AMOUNT SPENT</small><b>{creative.minimumSpend && creative.maximumSpend ? `${creative.minimumSpend}–${creative.maximumSpend}` : "NOT DISPLAYED"}</b><em>Range reported by Google</em></span><span><small>TIMES SHOWN</small><b>{creative.minimumViews && creative.maximumViews ? `${creative.minimumViews.toLocaleString()}–${creative.maximumViews.toLocaleString()}` : "NOT DISPLAYED"}</b><em>Not unique people</em></span></div>{profile && <p className="profile-context">Profile snapshot available for {profile.candidateName}: {formatMoney(profile.reportedSpend, profile.currency)} / {profile.reportedAdCount} ads · {profile.scopeLabel}.</p>}<a href={record.url} target="_blank" rel="noreferrer">Open public ad source ↗</a></aside>;
}

function PressDesk({ radar, onReturn }: { radar: any; onReturn: () => void }) {
  const reportable = (radar?.changes ?? []).filter((change: any) => change.reportable); const hasComparable = Boolean(radar?.captures?.ads && radar?.changes?.length);
  return <section className="press-desk"><div className="press-header"><div><span>PRESS DESK / SOURCE-BOUND REPORTING</span><h1>{radar?.race?.state ?? "Race"} evidence ledger</h1></div><button onClick={onReturn}>← Return to Voter Radar</button></div><div className="press-layout"><article className="ledger"><div className="ledger-bar"><b>Reportable changes</b><small>Thresholds are visible. Nothing is inferred.</small></div><table><thead><tr><th>CHANGE</th><th>EVIDENCE</th><th>RULE</th><th>STATUS</th></tr></thead><tbody>{reportable.length ? reportable.map((change: any) => <tr key={change._id}><td><span className="change-dot"/>{change.kind.replaceAll("_", " ")}</td><td>{change.evidenceUrls?.length ?? 0} direct source record{change.evidenceUrls?.length === 1 ? "" : "s"}</td><td>{change.rule}</td><td>Reportable</td></tr>) : <tr><td><span className="change-dot"/>Baseline / no qualified change</td><td>Stored public source records</td><td>Requires a second comparable snapshot and a stated threshold.</td><td>Not reportable</td></tr>}</tbody></table></article><aside className="investigator"><span>CONSTRAINED AI BRIEF</span><h2>What public campaign activity changed?</h2><div><b>WHAT CHANGED</b><p>{reportable.length ? `${reportable.length} threshold-qualified change${reportable.length === 1 ? " was" : "s were"} retained in the source ledger.` : hasComparable ? "No reportable change has met a published threshold." : "No reportable change has been confirmed; the first valid capture establishes a comparison baseline."}</p></div><div><b>WHAT SUPPORTS THIS</b><p>Only stored SerpApi records, capture timestamps, and their direct public source links are eligible for this brief.</p></div><div><b>WHAT WE CANNOT CONCLUDE</b><p>Ads and search readings do not establish persuasion, unique people reached, voter support, or likely election outcomes.</p></div><p className="ai-note"><i/>gpt-5-mini is constrained to stored civic evidence and declines political advice.</p></aside></div></section>;
}

export default function Home() { return convex ? <ConvexProvider client={convex}><FieldStation /></ConvexProvider> : <main className="config-error"><h1>Campaign Weather needs its Convex public URL.</h1></main>; }
